[package]
name = "basic-wasm"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
edition = "2018"

[lib]
name = "basic"
crate-type = ["cdylib"]

[dependencies]
basic = { path = ".." }
wasm-bindgen = "0.2.40"
